services:
  postgres:
    image: postgres:17.5-alpine
    container_name: postgres_17_slr
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: doslr
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
